# Generated by Django 5.2.7 on 2026-03-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_created_at_user_phone_user_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="developer_type",
            field=models.CharField(
                choices=[
                    ("none", "Профиль не указан"),
                    ("frontend", "Фронтенд"),
                    ("backend", "Бэкенд"),
                    ("fullstack", "Фулстек"),
                    ("devops", "DevOps"),
                    ("qa", "Тестировщик"),
                    ("android", "Android"),
                    ("db", "Разработчик БД"),
                ],
                default="none",
                help_text="Профиль разработчика, актуально для роли 'Разработчик'",
                max_length=20,
            ),
        ),
    ]
