# Generated by Django 5.2.7 on 2026-02-02 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_task_created_by_task_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий / детали')),
                ('is_done', models.BooleanField(default=False, verbose_name='Выполнен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='crm.task')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
