# Generated by Django 5.2.7 on 2026-02-13 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_taskcheckpoint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('slug', models.SlugField(help_text='Короткий идентификатор компании в URL', max_length=64, unique=True, verbose_name='Слаг компании')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('public_token', models.CharField(editable=False, help_text='Используется в публичной ссылке для заявок клиентов', max_length=32, unique=True, verbose_name='Токен публичной формы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='client_request',
            field=models.OneToOneField(blank=True, help_text='Исходная клиентская заявка (если проект создан по заявке)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='crm.clientrequest'),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Компания, для которой оставлена заявка', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_requests', to='crm.company'),
        ),
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Компания‑владелец проекта', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='crm.company'),
        ),
        migrations.CreateModel(
            name='CompanyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Владелец организации'), ('product_owner', 'Владелец продукта'), ('scrum_master', 'Scrum-мастер'), ('manager', 'Менеджер проектов'), ('developer', 'Разработчик')], default='developer', max_length=32, verbose_name='Роль в компании')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='crm.company', verbose_name='Компания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Участник компании',
                'verbose_name_plural': 'Участники компаний',
                'unique_together': {('company', 'user')},
            },
        ),
    ]
