# Generated by Django 5.2.7 on 2026-02-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_company_alter_project_client_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, max_length=255, verbose_name='Сфера деятельности'),
        ),
        migrations.AddField(
            model_name='company',
            name='join_code',
            field=models.CharField(blank=True, editable=False, help_text='Секретный код, который сотрудники вводят при регистрации', max_length=16, null=True, unique=True, verbose_name='Код для подключения сотрудников'),
        ),
        migrations.AddField(
            model_name='companymembership',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Администратор должен подтвердить участие пользователя в компании', verbose_name='Подтверждён администратором'),
        ),
    ]
