# Generated by Django 5.2.7 on 2026-02-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_company_industry_company_join_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companymembership',
            name='role',
        ),
        migrations.AddField(
            model_name='companymembership',
            name='is_developer',
            field=models.BooleanField(default=False, help_text='Может работать с задачами в проектах', verbose_name='Разработчик'),
        ),
        migrations.AddField(
            model_name='companymembership',
            name='is_manager',
            field=models.BooleanField(default=False, help_text='Может работать с заявками и проектами', verbose_name='Менеджер'),
        ),
        migrations.AddField(
            model_name='companymembership',
            name='is_owner',
            field=models.BooleanField(default=False, help_text='Администратор компании, имеет полный доступ', verbose_name='Владелец компании'),
        ),
    ]
