# Generated by Django 5.2.7 on 2026-03-09 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0010_requestcheckpoint_x_requestcheckpoint_y_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="KanbanColumnConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "К выполнению"),
                            ("in_progress", "В работе"),
                            ("review", "К проверке/QA"),
                            ("done", "Готово"),
                        ],
                        help_text="Какой статус задач отображается в колонке",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Отображаемое название колонки на доске",
                        max_length=255,
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Порядок отображения колонки слева направо"
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True, help_text="Показывать ли колонку на доске"
                    ),
                ),
                (
                    "wip_limit",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Максимальное количество задач в колонке (0 — без ограничения)",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kanban_columns",
                        to="crm.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "unique_together": {("project", "status")},
            },
        ),
    ]
