# Generated by Django 5.2.7 on 2026-03-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0016_companyreview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inappnotification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("task_comment", "Комментарий в задаче"),
                    ("task_assigned", "Назначена задача"),
                    ("task_updated", "Задача изменена"),
                    ("task_status_changed", "Изменён этап задачи"),
                    ("client_message", "Сообщение от клиента в заявке"),
                    ("new_client_request", "Новая заявка клиента"),
                    ("request_staff_message", "Сообщение по заявке от команды"),
                    ("sprint_started", "Спринт активирован"),
                    ("sprint_completed", "Спринт завершён"),
                    ("new_open_task", "Свободная задача"),
                    ("employee_join_pending", "Заявка сотрудника на вступление"),
                ],
                max_length=32,
            ),
        ),
    ]
